version: '3'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: news_management
    ports:
      - "5432:5432"
    restart: always
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    restart: always
    depends_on:
      - db