version: '3'
services:
  server:
    build: ./server/.
    ports:
      - "8761:8761"
    networks:
      - news-management-network
  config-server:
    build: ./config-server/.
    env_file:
      - .env
    ports:
      - "8888:8888"
    depends_on:
      - server
    networks:
      - news-management-network
  news-comment-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: news_management
    ports:
      - "5432:5432"
    restart: always
    networks:
      - news-management-network
  news-service:
    build: ./news-service/.
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - config-server
      - news-comment-db
    networks:
      - news-management-network
    restart: always
  user-db:
      image: postgres:15-alpine
      environment:
        POSTGRES_USER: username
        POSTGRES_PASSWORD: password
        POSTGRES_DB: news_management
      ports:
        - "5431:5431"
      restart: always
      networks:
        - news-management-network
  user-service:
      build: ./user-service/.
      ports:
        - "8081:8081"
      env_file:
        - .env
      depends_on:
        - config-server
        - user-db
      networks:
        - news-management-network
      restart: always

networks:
  news-management-network: