logging:
  level:
    org.springframework: DEBUG
jwt:
  key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
spring:
  datasource:
    url: jdbc:postgresql://db:5432/news_management
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: db/db.changelog-master.yaml
    url: jdbc:postgresql://db:5432/news_management
    user: username
    password: password
    driver-class-name: org.postgresql.Driver
    contexts: prod
springdoc:
  swagger-ui:
    path: /swagger-ui.html