logging:
  level:
    org.springframework: INFO
jwt:
  key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
spring:
  datasource:
    url: jdbc:h2:mem:news_management;DB_CLOSE_DELAY=-1
    username: username
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: h2
  liquibase:
    change-log: db/db.changelog-master.yaml
    url: jdbc:h2:mem:news_management;DB_CLOSE_DELAY=-1
    user: username
    password: password
    driver-class-name: org.h2.Driver
    contexts: dev
springdoc:
  swagger-ui:
    path: /swagger-ui.html