spring:
  datasource:
    url: jdbc:postgresql://db:5432/news_management
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://db:5432/news_management
    user: username
    password: password
    driver-class-name: org.postgresql.Driver
    baseline-on-migrate: true