server:
    port: 8888
    servlet:
        context-path: /config

eureka:
    client:
        service-url:
            defaultZone: http://server:8761/eureka
spring:
  application:
    name: service-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

management:
    health:
        livenessstate:
            enabled: true
        readinessstate:
            enabled: true
    endpoint:
        health:
          probes:
              enabled: true
